SUPABASE_URL=https://piscellbfojqfbarcfdr.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpc2NlbGxiZm9qcWZiYXJjZmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1Mjc2MTEsImV4cCI6MjA5MDEwMzYxMX0.tv9zljR4uDm_izFbLsc7SC8_HFB4KqYj7SQf2eJsxaQ
